name: XVir
channels:
  - pytorch       # For PyTorch
  - defaults
  - conda-forge
dependencies:
  - keras==3.3.3
  - matplotlib==3.7.0
  - numpy==1.23.5
  - pandas==1.5.3
  - scikit-learn==1.2.1
  - scipy==1.10.0
  - tensorflow==2.16.1
  - tqdm==4.64.1
  - pytorch==2.1.0        # Upgraded to satisfy keras's requirement
  - pip
  - pip:
      - tflearn==0.5.0
